# Generated by Django 3.1.7 on 2021-03-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210310_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fecha',
            new_name='superpoder',
        ),
    ]
